### ISSUE TITLE
Gerber  problem

### ISSUE THREAD

**Issue by www97221** [WB2CBA/uSDX-mOnO#1]
Firstly, thank you to the author for their development and sharing. I would like to know where to find the Gerber files for RF boards and mian boards?

**Comment by WB2CBA** [comment]
Sorry for the late reply, I designed usdx mono for a friend to be a kit to market and all rights of the design is his. He doesn’t want me to release any data including gerbers. Sorry for that.73Barb WB2CBAOn Oct 11, 2023, at 03:16, www97221 ***@***.***> wrote:﻿
Firstly, thank you to the author for their development and sharing. I would like to know where to find the Gerber files for RF boards and mian boards?
